################################################################################
# Copyright (c) 2021 ContinualAI Research                                      #
# Copyrights licensed under the CC BY 4.0 License.                             #
# See the accompanying LICENSE file for terms.                                 #
#                                                                              #
# Date: 09-02-2021                                                             #
# Author(s): Gabriele Graffieti                                                #
# E-mail: contact@continualai.org                                              #
# Website: clair.continualai.org                                               #
################################################################################

channels:
- conda-forge
dependencies:
- psutil
- tensorboard
- scikit-learn
- matplotlib
- numpy
- conda-forge::quadprog
- tqdm
- pip
- pip:
    - pytorchcv
    - googledrivedownloader
