################################################################################
# Copyright (c) 2021 ContinualAI.                                              #
# Copyrights licensed under the MIT License.                                   #
# See the accompanying LICENSE file for terms.                                 #
#                                                                              #
# Date: 09-02-2021                                                             #
# Author(s): Gabriele Graffieti                                                #
# E-mail: contact@continualai.org                                              #
# Website: avalanche.continualai.org                                           #
################################################################################

channels:
- conda-forge
dependencies:
- psutil
- conda-forge::gputil
- scikit-learn
- matplotlib
- numpy
- conda-forge::quadprog
- tqdm
- wandb
- tensorboard
- conda-forge::pycocotools
- pip
- pip:
    - pytorchcv
    - gdown
    - ctrl-bench