################################################################################
# Copyright (c) 2021 ContinualAI.                                              #
# Copyrights licensed under the MIT License.                                   #
# See the accompanying LICENSE file for terms.                                 #
#                                                                              #
# Date: 1-05-2020                                                              #
# Author(s): Vincenzo Lomonaco                                                 #
# E-mail: contact@continualai.org                                              #
# Website: avalanche.continualai.org                                           #
################################################################################

channels:
- conda-forge
dependencies:
- pip
- psutil
- conda-forge::gputil
- wandb
- tensorboard>=1.15
- scikit-learn
- matplotlib
- numpy
- conda-forge::quadprog
- tqdm
- conda-forge::pycocotools
- conda-forge::torchmetrics
- conda-forge::pycodestyle
- sphinx
- sphinx_rtd_theme
- conda-forge::astroid=2.4.2
- conda-forge::sphinx-autoapi
- pip:
    - pytorchcv
    - gdown
    - ctrl-benchmark
    - higher
    - gym
    - lvis
