################################################################################
# Copyright (c) 2021 ContinualAI.                                              #
# Copyrights licensed under the MIT License.                                   #
# See the accompanying LICENSE file for terms.                                 #
#                                                                              #
# Date: 28-01-2021                                                             #
# Author(s): Gabriele Graffieti                                                #
# E-mail: contact@continualai.org                                              #
# Website: avalanche.continualai.org                                           #
################################################################################


name: PEP8 checking
# This workflow is triggered on pushes to the repository.
on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/pep8.yml'
      - '.pylintrc'
  pull_request_target:
    branches:
      - master
    paths:
      - '**.py'
      - '.github/workflows/pep8.yml'
      - '.pylintrc'

jobs:
  check:
    name: check pep8
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - name: check out the repo (push)
        if: github.event_name == 'push'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: check out the repo (PR)
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: install pycodestyle
        run: pip install pycodestyle
      - name: check pep8 in source files
        run: |
          pycodestyle avalanche tests examples --exclude "examples/tvdetection/**" > pep8_report.txt
          cat pep8_report.txt
      - name: send PR message
        if: failure() && github.event_name == 'pull_request_target' && github.repository == 'ContinualAI/avalanche'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            var message = "Oh no! It seems there are some PEP8 errors! ðŸ˜•\nDon't worry, you can fix them! ðŸ’ª\nHere's a report about the errors and where you can find them:\n\n```\n"
            var fs = require("fs");
            var text = fs.readFileSync("pep8_report.txt", "utf-8");
            var text_complete = message.concat(text, "\n```")
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: text_complete
            })
