name: sphinx compilation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build_sphinx_doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false
      - name: install conda dependencies
        run: |
          conda env create -f environment.yml
      - name: install sphinx
        run: |
          source activate avalanche-env
          conda install -c anaconda sphinx
          conda install -c anaconda sphinx_rtd_theme
          conda list
      - name: compile documentation
        run: |
          source activate avalanche-env
          conda list
          sphinx-apidoc -f -d 4 -o docs/api/ avalanche/
          sphinx-build -b dirhtml docs/ doc_html/