################################################################################
# Copyright (c) 2021 ContinualAI.                                              #
# Copyrights licensed under the MIT License.                                   #
# See the accompanying LICENSE file for terms.                                 #
#                                                                              #
# Date: 22-03-2021                                                             #
# Author(s): Gabriele Graffieti                                                #
# E-mail: contact@continualai.org                                              #
# Website: avalanche.continualai.org                                           #
################################################################################

name: test coverage coverall

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - '.github/workflows/test-coverage-coveralls.yml'
      - 'environment.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**.py'
      - '.github/workflows/test-coverage-coveralls.yml'
      - 'environment.yml'

jobs:
  unit-test:
    if: github.repository == 'ContinualAI/avalanche'
    name: unit test
    runs-on: ubuntu-latest
    container:
      image: ggraffieti/avalanche-ds:latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.6", "3.7", "3.8", "3.9"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: copy dataset in correct folder
        run: cp -r /~/.avalanche /github/home
      - name: install conda environment < 3.9
        if: matrix.python-version != '3.9'
        run: |
          conda create -n avalanche-env python=${{ matrix.python-version }} -c conda-forge
          conda activate avalanche-env
          conda install pytorch torchvision cpuonly -c pytorch -y
          conda env update --file environment.yml
      - name: install conda environment = 3.9
        if: matrix.python-version == '3.9'
        run: |
          conda create -n avalanche-env python=${{ matrix.python-version }} -c conda-forge
          conda activate avalanche-env
          conda install pytorch torchvision cpuonly -c pytorch -c=conda-forge -y
          conda env update --file environment.yml
      - name: install coverage.py and coverralls
        run: |
          conda activate avalanche-env
          pip install coverage
          pip install coveralls
      - name: python unit test
        id: unittest
        run: |
          conda activate avalanche-env
          FAST_TEST=True USE_GPU=False coverage run -m unittest
      - name: Upload coverage data to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true

  coveralls:
    if: github.repository == 'ContinualAI/avalanche'
    name: Indicate completion to coveralls.io
    needs: unit-test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        run: |
          pip3 install --upgrade coveralls
          coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
